from datetime import datetime, timezone
from typing import List, Dict, Optional
import uuid
from app.research.evidence_graph.repository import EvidenceGraphRepository
from app.research.governance.service import GovernanceService
from app.research.governance.models import ResearchAuditEvent
from app.research.knowledge_intelligence.models import ResearchKnowledgeClaim
from app.research.planner.models import ResearchQuestionCandidate, ResearchDecisionState
from app.research.reasoning.models import ResearchReasoningResult, ConclusionType, ResearchReasoningSummary
from app.research.reasoning.engine import ReasoningEngine

class ReasoningService:
    def __init__(self, graph_repo: EvidenceGraphRepository = None, gov_service: GovernanceService = None):
        self.graph_repo = graph_repo or EvidenceGraphRepository()
        self.gov_service = gov_service or GovernanceService()
        self.engine = ReasoningEngine(self.graph_repo)
        self._persisted_results: Dict[str, ResearchReasoningResult] = {}
        self._generated_questions: Dict[str, ResearchQuestionCandidate] = {}

    def reason_over_claim(self, claim: ResearchKnowledgeClaim, as_of: datetime) -> List[ResearchReasoningResult]:
        as_of_utc = as_of.replace(tzinfo=timezone.utc) if as_of.tzinfo is None else as_of
        
        # 1. Run inference
        results = self.engine.reason_over_neighborhood(claim, as_of_utc)
        
        # 2. Process results (Generate gaps, questions, audit)
        for res in results:
            if res.reasoning_id not in self._persisted_results:
                self._persisted_results[res.reasoning_id] = res
                
                # Governance audit
                self.gov_service.audits.append(ResearchAuditEvent(
                    event_type="RESEARCH_REASONING_GENERATED",
                    research_identity_hash="reasoning_service",
                    source_id=res.reasoning_id,
                    reason=f"Generated reasoning {res.conclusion_type.value} via {res.rule_id}",
                    as_of=as_of_utc
                ))
                
                # Phase 32 Question Generation
                if res.conclusion_type in [ConclusionType.REQUIRES_REVALIDATION, ConclusionType.REQUIRES_INTERACTION_TEST, ConclusionType.REQUIRES_REPLICATION, ConclusionType.REQUIRES_SCOPE_EXPANSION]:
                    qid = f"rq_{uuid.uuid4().hex[:8]}"
                    q = ResearchQuestionCandidate(
                        question_id=qid,
                        research_identity="reasoning_gap",
                        research_question=f"Does the finding hold up against {res.conclusion_type.value}? ({res.canonical_statement})",
                        related_conclusions=res.source_claim_ids,
                        evidence_strength=0.0,
                        expected_information_gain=0.8,
                        research_value=0.8,
                        priority_score=0.8,
                        priority_reason=f"Generated by Phase 53 Reasoning {res.rule_id}",
                        created_at=as_of_utc,
                        as_of=as_of_utc,
                        status=ResearchDecisionState.REVIEW_REQUIRED
                    )
                    res.research_question_ids.append(qid)
                    self._generated_questions[qid] = q

        return results
        
    def get_summary(self, as_of: datetime) -> ResearchReasoningSummary:
        as_of_utc = as_of.replace(tzinfo=timezone.utc) if as_of.tzinfo is None else as_of
        valid_results = [r for r in self._persisted_results.values() if r.as_of <= as_of_utc]
        
        s = ResearchReasoningSummary(
            total_reasoning_results=len(valid_results),
            supported_inferences=sum(1 for r in valid_results if r.conclusion_type == ConclusionType.SUPPORTED_INFERENCE),
            conditional_inferences=sum(1 for r in valid_results if r.conclusion_type == ConclusionType.CONDITIONAL_INFERENCE),
            conflicted_inferences=sum(1 for r in valid_results if r.conclusion_type == ConclusionType.CONFLICTED_INFERENCE),
            insufficient_evidence=sum(1 for r in valid_results if r.conclusion_type == ConclusionType.INSUFFICIENT_EVIDENCE),
            revalidation_required=sum(1 for r in valid_results if r.conclusion_type == ConclusionType.REQUIRES_REVALIDATION),
            replication_required=sum(1 for r in valid_results if r.conclusion_type == ConclusionType.REQUIRES_REPLICATION),
            scope_expansion_required=sum(1 for r in valid_results if r.conclusion_type == ConclusionType.REQUIRES_SCOPE_EXPANSION),
            interaction_tests_required=sum(1 for r in valid_results if r.conclusion_type == ConclusionType.REQUIRES_INTERACTION_TEST),
            as_of=as_of_utc
        )
        s.research_gap_count = sum(len(r.research_question_ids) for r in valid_results)
        return s

    def get_questions_for_review(self) -> List[ResearchQuestionCandidate]:
        return list(self._generated_questions.values())
