from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, field_validator

class MarketBar(BaseModel):
    """Represents a single OHLCV market bar."""
    symbol: str = Field(..., min_length=1)
    timestamp: datetime
    open: float = Field(..., gt=0)
    high: float = Field(..., gt=0)
    low: float = Field(..., gt=0)
    close: float = Field(..., gt=0)
    volume: float = Field(..., ge=0)
    
    @field_validator("high")
    @classmethod
    def check_high(cls, v, info):
        if "open" in info.data and v < info.data["open"]:
            pass # High should theoretically be >= open, but we do a strict check below
        return v
        
    # We could add a model_validator to ensure high >= low, high >= open, etc.

class SignalScore(BaseModel):
    """Deterministic score for a trading signal."""
    score: float = Field(..., ge=0.0, le=100.0)
    components: dict[str, float]

class MarketRegimeResult(BaseModel):
    """Result of market regime detection."""
    regime: str = Field(..., description="e.g. TRENDING_UP, TRENDING_DOWN, RANGE_BOUND, HIGH_VOLATILITY, INSUFFICIENT_DATA")
    confidence: float = Field(..., ge=0.0, le=1.0)

class SentimentResult(BaseModel):
    score: float = Field(..., ge=-1.0, le=1.0)
    label: str = Field(..., description="POSITIVE, NEUTRAL, or NEGATIVE")
    confidence: float = Field(..., ge=0.0, le=1.0)
    source_count: int = Field(..., ge=0)
    timestamp: datetime

class NewsArticle(BaseModel):
    id: str
    timestamp: datetime
    source: str
    title: str
    summary: str
    symbols: list[str]
    url: Optional[str] = None
    sentiment: Optional[SentimentResult] = None
    relevance: Optional[float] = None

class MarketIntelligence(BaseModel):
    symbol: str
    timestamp: datetime
    sentiment: SentimentResult
    relevant_articles: int
    anomaly_status: list[str]
    risk_flags: list[str]
    fakeout_risk: str = "UNKNOWN"

class TradingSignal(BaseModel):
    """A trading signal generated by a strategy or ensemble."""
    symbol: str
    timestamp: datetime
    direction: str = Field(..., description="'LONG' or 'SHORT'")
    strategy: str
    confidence: float = Field(..., ge=0.0, le=1.0)
    entry_price: Optional[float] = Field(None, gt=0)
    stop_loss: Optional[float] = Field(None, gt=0)
    take_profit: Optional[float] = Field(None, gt=0)
    reason: str
    score: Optional[SignalScore] = None
    regime: Optional[MarketRegimeResult] = None
    intelligence: Optional[MarketIntelligence] = None

    @field_validator("direction")
    @classmethod
    def validate_direction(cls, v):
        v = v.upper()
        if v not in ("LONG", "SHORT"):
            raise ValueError("Direction must be 'LONG' or 'SHORT'")
        return v

class RiskDecision(BaseModel):
    """The outcome of a risk evaluation for a pending trade."""
    approved: bool
    requested_risk: float = Field(..., ge=0)
    allowed_risk: float = Field(..., ge=0)
    position_size: float = Field(..., ge=0)
    rejection_reason: Optional[str] = None
    relevant_limit: Optional[str] = None

class TradeRecord(BaseModel):
    """A record of a completed or active trade."""
    id: str
    symbol: str
    direction: str
    entry_price: float = Field(..., gt=0)
    stop_loss: Optional[float] = Field(None, gt=0)
    take_profit: Optional[float] = Field(None, gt=0)
    quantity: float = Field(..., gt=0)
    status: str = Field(..., description="e.g., 'OPEN', 'CLOSED', 'PENDING'")
    timestamp: datetime
    
    @field_validator("direction")
    @classmethod
    def validate_direction(cls, v):
        v = v.upper()
        if v not in ("LONG", "SHORT"):
            raise ValueError("Direction must be 'LONG' or 'SHORT'")
        return v
